### ISSUE TITLE
Shows Hexadecimal values instead of real data

### ISSUE THREAD

**Issue by Prid13** [dogechain-lab/leveldb-tools#1]
Cool tool :) Would love some auto-generated binaries for different platforms, like Windows 😇

But it's not working for me. When using `list`, I only get a hex value in return. And for showing the value to a key, the program recognizes the key I input, but the output is still unreadable hex value:

![image](https://github.com/dogechain-lab/leveldb-tools/assets/27897747/ca0c376f-047e-41d0-ad86-bafab2cb10c6)

**Comment by DarianShawn** [comment]
It is only for general usage.
Data formats are diverse: jSON, RLP, binary or any other type.
So we didn't provide any deserialization options here.

Any PR is welcome if you could provide some options to it. :)

**Comment by Prid13** [comment]
Thanks for replying :) I was just testing a bunch of tools at that time to be able to read chrome extension ldb data, and I did find a bunch of others (among which [this one](https://github.com/cions/leveldb-cli) suits my needs the most), so while I'd love to contribute, I unfortunately lack the skills in this area to help out, and unfortunately also motivation as I've found another solution that works for me 😅

But thanks for your effort and your reply, appreciate it ⭐

**Comment by DarianShawn** [comment]
You're welcome.
Glad that your requirement is met.
